CREATE TABLE public.part (
    id integer NOT NULL,
    sort integer,
    user_created uuid,
    date_created timestamp with time zone,
    date_updated timestamp with time zone,
    title character varying(255),
    "order" integer,
    content text,
    quiz integer,
    "time" integer,
    passage integer DEFAULT 0,
    simplified_content text,
    question_count smallint DEFAULT 0,
    listen_from integer,
    listen_to integer,
    instruction integer,
    task_instruction text,
    transcription jsonb,
    file_id uuid
);

CREATE TABLE public.question (
    id integer NOT NULL,
    status character varying(255) DEFAULT 'draft'::character varying NOT NULL,
    sort integer,
    user_created uuid,
    date_created timestamp with time zone,
    user_updated uuid,
    date_updated timestamp with time zone,
    title character varying(255),
    content text,
    type character varying(255),
    single_choice_radio json,
    selection json,
    mutilple_choice json,
    gap_fill_in_blank text,
    quiz integer,
    selection_option json,
    locate character varying(255),
    "order" integer,
    explain text,
    description text,
    content_writing text,
    part integer,
    time_to_think integer,
    listen_from integer,
    question_type text,
    instruction text,
    writing_graph_image uuid,
    writing_graph_description text,
    writing_graph_type smallint,
    audio_url text,
    time_limit integer DEFAULT 30,
    max_words integer,
    min_words integer,
    question_set_id integer,
    correct_answer text,
    correct_answers text[],
    text text,
    options jsonb,
    locate_info jsonb
);

CREATE TABLE public.question_set (
    id integer NOT NULL,
    part_id integer,
    user_created uuid NOT NULL,
    date_created timestamp with time zone NOT NULL,
    user_updated uuid,
    date_updated timestamp with time zone,
    question_type text NOT NULL,
    question_count integer NOT NULL,
    title text,
    description text NOT NULL,
    content text,
    option_title text,
    options jsonb,
    allow_reuse boolean,
    max_selections integer,
    sort integer
);

CREATE TABLE public.quiz (
    id integer NOT NULL,
    status character varying(255) DEFAULT 'draft'::character varying NOT NULL,
    sort integer,
    user_created uuid,
    date_created timestamp with time zone,
    user_updated uuid,
    date_updated timestamp with time zone,
    type integer,
    content text,
    title character varying(255),
    "order" integer,
    "time" integer,
    listening uuid,
    description text,
    instruction integer,
    quiz_code character varying(255),
    limit_submit integer,
    question text,
    samples text,
    thumbnail uuid,
    vote_count integer DEFAULT 0 NOT NULL,
    quiz_type smallint,
    full_id integer,
    is_test boolean,
    mode smallint DEFAULT 0,
    simplified_id integer,
    mock_test_id integer,
    mock_test_type integer,
    total_submitted integer DEFAULT 0,
    short_description text,
    practice_listing_priority integer DEFAULT 0,
    is_public boolean DEFAULT true,
    writing_task_type integer,
    meta jsonb,
    prompt_set_id integer,
    speaking_part_type integer,
    speaking_topic_id integer,
    instruction_audio uuid,
    CONSTRAINT quiz_vote_count_check CHECK ((vote_count >= 0))
);

CREATE TABLE public.quiz_part (
    id integer NOT NULL,
    quiz_id integer,
    part_id integer,
    sort integer DEFAULT 0
);