apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: CI_GROUP_NAME-CI_PROJECT_NAME
  namespace: NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: CI_GROUP_NAME-CI_PROJECT_NAME
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
