YOUR_API_BAND_SCORE_TASK_1_GPT = ""
YOUR_API_BAND_SCORE_TASK_2_GPT = ""
YOUR_API_GEMINI = ""
YOUR_API_CLAUDE = ""
POSTGRES__HOST = ""
POSTGRES__PASS = ""
POSTGRES__USER = ""
POSTGRES__DB = ""
JWT_SECRET_KEY = ""
REDIS__PORT=6379
REDIS__HOST=""
REDIS__DB=0
YOUR_API_OPENROUTER = ""
RABBITMQ_HOST = ""
RABBITMQ_PORT = ""
RABBITMQ_USER = ""
RABBITMQ_PASSWORD = ""